### PR TITLE
doc: add link to arm-unknown-linux-gnueabihf tar

### PR DESCRIPTION
**Pull request by EarthyOrange**

### CODE REVIEW

**Comment by hiszpanski** [comment]
Awesome! Thanks for taking this on -- simple program using floats seems to work on an RPi 3B+. A couple comments:

- Permissions are currently u-w. Can you run `chmod -R u+w` on the directory and then recreate the tarball?
- Do you mind if the .xz file is hosted in this repo so that everything's in one spot?

**Comment by EarthyOrange** [comment]
Can you add me as a contributor to the repo? I can upload the tar to the release tag.

**Comment by EarthyOrange** [comment]
The tarball was created again after running the `chmod` command. It has been uploaded to the 8.3.0 release tag on this main repo.

**Comment by hiszpanski** [comment]
Looks great -- thanks!

**Pull request merged**
